version: '3'


services:
  server:
          build: ./
          expose:
              - 8080
          environment:
              - NODE_ENV=production
              - MONGODB_USERNAME=myUserAdmin
              - MONGODB_PASSWORD=pass
          ports:
              - 8080:8080
          volumes:
              - ./:/srv/app/admin-server
              - /srv/app/admin-server/node_modules
          depends_on:
              - mongodb    
          command: npm run start       
  mongodb:
          image: mongo
          volumes:
              - data-volume:/data/db
              - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
          ports:
              - "27017:27017"              
volumes:
  data-volume:
# obs: named volumes should be listed here.
# Just a reminder : anonymous volumes, and bind mounts don't need to be specified here.